re-enable example project test

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -95,12 +95,12 @@ jobs:
           cd example_project;
           DJANGO_VERSION="${{ matrix.django }}"
           EXAMPLE_PROJECTS_DJANGO_VERSION=$(grep -i "django[^-]" requirements.txt | cut -d "=" -f 2)
-#          if [ "${DJANGO_VERSION:0:3}" = "${EXAMPLE_PROJECTS_DJANGO_VERSION:0:3}" ]; then
-#              python -Wa manage.py makemigrations --check --dry-run;
-#          elif [ -z "${EXAMPLE_PROJECTS_DJANGO_VERSION}" ]; then
-#              echo "Could not determine which version of Django the example project supports."
-#              exit 1
-#          fi;
+          if [ "${DJANGO_VERSION:0:3}" = "${EXAMPLE_PROJECTS_DJANGO_VERSION:0:3}" ]; then
+              python -Wa manage.py makemigrations --check --dry-run;
+          elif [ -z "${EXAMPLE_PROJECTS_DJANGO_VERSION}" ]; then
+              echo "Could not determine which version of Django the example project supports."
+              exit 1
+          fi;
 
           export DATABASE_URL=postgres://postgres:postgres@localhost/django_guardian
           python -Wa manage.py test;
